api_id = "Your desktop TG app api_id"
api_hash = "Your desktop TG app api_hash"
device_model = "Your desktop TG app device_model"
system_version = "Your desktop system_version"
app_version = "Your desktop TG app_version"
lang_code = "Your desktop TG app lang_code"
system_lang_code = "Your desktop system_lang_code"
